 CREATE TABLE markets (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    market_name TEXT NOT NULL,
    hero_image TEXT,
    schedule TEXT NOT NULL,
    market_location TEXT NOT NULL,
    summary TEXT NOT NULL,
    market_description TEXT NOT NULL
);