CREATE TABLE vendors (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vendor_name TEXT NOT NULL,
    vendor_description TEXT NOT NULL,
    market_stall TEXT NOT NULL,
    market_id INTEGER
        REFERENCES markets(id) ON DELETE RESTRICT NOT NULL
);