CREATE TABLE products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name TEXT NOT NULL,
    product_description TEXT
);

CREATE TYPE product_category AS ENUM
(
    'fruit',
    'vegetable',
    'nuts and grains',
    'poultry',
    'meat',
    'seafood',
    'other'
);

ALTER TABLE products
  ADD COLUMN
    kind product_category;