CREATE TABLE products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name TEXT NOT NULL,
    product_description TEXT
);

CREATE TYPE product_category AS ENUM
(
    'Fruit',
    'Vegetable',
    'Nuts & Grains',
    'Poultry',
    'Meat',
    'Seafood',
    'Other'
);

ALTER TABLE products
  ADD COLUMN
    kind product_category;
