CREATE TABLE price_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    price NUMBER NOT NULL,

    article_id INTEGER
        REFERENCES blogful_articles(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES blogful_users(id) ON DELETE CASCADE NOT NULL    
);